r-lib/profvis

- R/parse.R
- R/profvis.R
- man/profvis.Rd
Minor additions to control the behavior of output files:
- Read `profvis.output_path` option to define the default output location of profiles. This option can be set through `options(profvis.output_path = "<path>")`
- Read 'profvis.keep_output` to keep the temporary profile even after profvis closes. This enables further processing by the host of profvis. This option can be set through `options(profvis.keep_output = TRUE)`
- Return the `output_path` under the widget structure to allow the host to retrieve profile names generated by profvis. This data can be accessed with `profvis(pause(1))$x$message$prof_output`
- Fix to parsing profiles that contain no sources and no `<expr>`. Hit this corner case while running:
```
Rprof("~/tmp/test.rprof")
pause(1)
Rprof(NULL)
profvis(prof_input = …
```
> Add support to control output file behavior

- DESCRIPTION
The build machine is using R 2.11.1 which requires the `DESCRIPTION` file to contain these fields. Any chance we can merge this to avoid building from this branch?
> add author and maintainer fields to support r-2

- inst/htmlwidgets/lib/profvis/profvis.js
Small change to allow hosts to get notified of a source file being double clicked from either: the flame graph or code table.
> add support to notify profvis host of source file events

- R/profvis.R
Two options to complete integration with the ide:
- `profvis.print`: Allows hosts to customize the behavior of `print` (Used to open the profile pane in the ide);
- `profvis.prof_extension`: Allows hosts to customize the default extension (`.rprof` in the ide)
> add support to customize print behavior and extension

- inst/htmlwidgets/lib/profvis/profvis.css
- inst/htmlwidgets/lib/profvis/profvis.js
Adds a message for profiles that have no sources available:
> add message for profiles with sources not available

- inst/htmlwidgets/lib/profvis/profvis.js
Typo in quote using backtick character instead is causing script error in windows os, replacing for standard single quote.
> use single quotes instead of backtick character

- DESCRIPTION
- inst/htmlwidgets/lib/profvis/profvis.js
Add tooltip to help understand users why the code panel does not necessarily need to add up to a 100%. That would be the case for a single entry point `call-stack` graph, which is not the case here.
> add tooltip to describe role of execution percentage

- DESCRIPTION
- R/parse.R
- inst/htmlwidgets/lib/profvis/profvis.js
Paths are stored in their relative form (e.g. `~/temp/test.R`) which is fine; however, other scenarios like project sharing, require full paths to function properly. This adds a `normpath` property to `x$message$files` collection to track the normalized path (e.g. `/users/name/temp/test.R`)
> add support to track the normalized sources path

- inst/htmlwidgets/lib/profvis/profvis.css
- inst/htmlwidgets/lib/profvis/profvis.js
While expanding data if the memory column is off, `<td>` elements are not hidden which causes the table to partially add back the memory column. Fix is to set the state of all memory related cells each time the data table rows are updated.
Also, removing unused code from the treemap visualization.
> fix visual issue while hiding memory and expanding data and remove treemap

- R/parse.R
Straightforward fix; however, this fix is on the memory parsing script which impacts any `profivs` operation. Most likely, a fix that can wait after the preview build.
**Problem**: `Rprof` files use `:` to delimit memory fields in each sample; however, some callstacks can contain `:` in their expressions. The side effect of the current code is that any entry in the callstack with `:` will get split and considered as multiple calls. So for instance the callstack `a -> b::c -> d` will be considered as `a -> b -> '' -> c - > d`. This will add empty labels to the callstack but I have not able to find any other side effects (UI still works correctly and memory gets assigned to parent nodes).
**Fix**: The fix is to first split by ` ` and then the first column by `:`. The first column contains …
> parse memory correctly when callstack contains colons

- inst/htmlwidgets/lib/profvis/profvis.js
Minor fix to re-trigger resize while switching between "Flame Graph" and "Data" tabs. Otherwise, the split-bar ends up in the wrong position and the flame graph no re-rendered.
> trigger panel resize on view change

- DESCRIPTION
- R/profvis.R
- inst/htmlwidgets/lib/profvis/profvis.css
- inst/htmlwidgets/lib/profvis/profvis.js
- man/print.profvis.Rd
- man/profvis.Rd
This pr splits the memory column from total allocation, into allocations and deallocations.
Comment from @hadley in previous PR: "You might also want to have an example line that both allocates and frees memory - if you're not already, you should probably be aggregating allocs and frees separately." (https://github.com/rstudio/profvis/pull/39).
At that time, I was not convinced we needed to show both; however, after going through some of @wch memory profiling exercises (https://support.rstudio.com/hc/en-us/articles/218221837#additional-resources) this has become apparent.
The problem is that a lot of times memory will be allocated/deallocated on the same path/function and the profiler will only report the net allocation; it's hard to explain in the memory profiler examples why this is an …
> add support to display memory deallocs and allocs

- DESCRIPTION
- inst/htmlwidgets/lib/profvis/profvis.css
- inst/htmlwidgets/lib/profvis/profvis.js
Feedback from @jcheng5:
1. Tree view causes text selection.
2. While on edge of the cell, the pointer and label start wrapping.
3. "Calls" vs "Samples"?
4. `profvis(shiny::runExample("03_reactivity"))` and data view
5. Consistent font for profvis.
Regarding (3), I meant "Calls" since it's close-enough that I believe it's useful. However, added a "Calls are approximate since this is a sample-based profile" hover message. Surprisingly, this happens to be very accurate in various situations.
Here is an update with the (4) app running:
> Improve data view for shiny usage and visual improvements

- R/parse.R
@hadley and @wch: I've been meaning to send this change for consideration for a while, so here it is. Would love to know your thoughts...
The way memory is tracked in `rprof` is by adding up: **big** heap objects, **small** heap objects and **expression** nodes. It's worth taking a look at `get_current_mem` from https://github.com/wch/r-source/blob/e5b21d0397c607883ff25cca379687b86933d730/src/main/memory.c#L1923
The way we calculate memory is as follows: 
```
memalloc <- sum(as.integer(sample[1:3])) / 1024 ^ 2
```
This calculation tracks all the memory provided by `rprof` and also mimics the implementation from `lineprof` (see https://github.com/hadley/lineprof/blob/972e71dca0087ed8452e21f914fd612376075d5b/R/profile.R#L67)
That said, I've notice that is very unintuitive the memory …
> stop tracking expressions allocation

- inst/htmlwidgets/lib/profvis/profvis.js
@wch: Adds allocs and deallocs to flame graph infobox as follows:
Notice that in the previous profile the flame graph and code view both match in allocs/de-allocs.
However, if more than one top-level call maps to the same line, these two numbers won't map 1:1 but adding each call should add in allocs/deallocs to the selected line in the code viewer. Consider the following profile for instance:
> #49 display allocs and deallocs under infobox

- DESCRIPTION
- R/parse.R
Took a look at the r-sources... while it's true that a pointer is involved, it happens to be the case that the r-sources use an union between an SEXP and a double to translate vsize into MB. This is more obvious with an example, running this:
```
profvis::profvis({
profvis::pause(0.01)
data <- rnorm(1024 ^ 2)
profvis::pause(0.01)
})
```
on a x64 machines yields 8Mb, which is correct:
However, on a x86 machine, this is not the case since `.Machine$sizeof.pointer` becomes 4, but a double is still 8 bytes:
Therefore, seems the correct fix is to multiply this by 8 since the union contains a variable length pointer (4 - 8  bytes depending on the processor) but the double remains a double across both architectures.
Would appreciate if @wch and @hadley could take a look at the comments and …
> fix memory calculation

- R/parse.R
Need empty mem_data vector even without memory profiling.
> Fix display of timing-only profile data

- R/file_contents.R
This is the simpler part of #68 -- it just helps ensure that failures to load a package namespace (for cases where the package name was mis-inferred) no longer cause a hard error.
> attempt to load namespace before caching

- inst/htmlwidgets/lib/profvis/profvis.js
to allow seeing the relevant details much faster.
This PR contains of two components: sorting tree nodes by time descending (commit 1), and auto-expansion (commits 2 and 3).
The auto-expansion will always expand the first node until a leaf is reached. Because the nodes are sorted by time, this will automatically focus on the most important piece of code that is likely in need of profiling.
Example run: http://rpubs.com/krlmlr/profvis-82.
Fixes #82.
Closes #50.
> Auto-expand tree nodes in "Data" pane

- DESCRIPTION
- NEWS.md
- R/profvis.R
- man/print.profvis.Rd
- man/profvis.Rd
Maps to the `filter.callframes` argument added to `Rprof()` in R 4.0. Turned on by default.
Closes #102.
> Add `simplify` argument

- R/profvis.R
- tests/testthat/_snaps/profvis.md
- tests/testthat/test-profvis.R
* Ensure that we always terminate `RProf()` even if the expr errors
* Make it a bit more clear how expr works (we regenerate the lazy binding on every iteration)
* Ensure we always set lines, even if the expr errors. (This is what lead to the mystifying lines is not a character vector error)
> Clarify the main profvis loop
